### ISSUE TITLE
appremoting.cs question

### ISSUE THREAD

**Issue by yinalger** [microsoft/OpenXR-Unity-MixedReality-Samples#106]
I connected the hololens2,the editor console return [AppRemotingPlugin] Connect InitializeLoader.No conect build.
I tracked the problem and found XRGeneralSettings.Instance.Manager.InitializeLoader() can not create XRGeneralSettings.Instance.Manager.activeLoader.More information is: InitializeInternal()->CreateSubsystems()->CreateSubsystem<XRDisplaySubsystemDescriptor, XRDisplaySubsystem>(s_DisplaySubsystemDescriptors, "OpenXR Display");->            base.CreateSubsystem<TDescriptor, TSubsystem>(descriptors, id); -> subsys = descriptor.Create(); can not work.
Hope to get a reply quickly.

**Comment by yl-msft** [comment]
@yinalger ,  the message indicate the app remoting cannot connect to remote player properly.  But without logs or traces, I cannot tell what's wrong on your setup.

**Comment by yinalger** [comment]
Thank you for your reply.
For UWP,I found it only works at runtime.I built the same project and set the holographic remote Win32 App as the PC platform.No connection was built.I thought it could be the same reason as playmoderemoting.cs which return TransportConnectionFailed.
Anyway,now I can connect to the Hololesn2.I will close the issue and try another way.Thans for the reply.
