### ISSUE TITLE
Haptic binding not avaliable for HP Reverb G2

### ISSUE THREAD

**Issue by Reahreic** [microsoft/OpenXR-Unity-MixedReality-Samples#113]
It looks as though the HP Reverb G2 Controller Profile from MSFT's Mixed Reality OpenXR Plugin (1.4.2 and 1.5.1) is misconfigured.

Specifically, it looks as though the profile is missing the following declarations pertaining to haptics:

Before the 'protected override void FinishSetup()' method declaration ~Line 154

`/// <summary>
/// A <see cref="HapticControl"/> that represents the <see cref="HTCViveControllerProfile.haptic"/> binding.
/// </summary>
[Preserve, InputControl(usage = "Haptic")]
public HapticControl haptic { get; private set; }`
 
Within the 'protected override void FinishSetup()' method declaration ~Line 178
`haptic = GetChildControl<HapticControl>("haptic");'

At the end of the ActionMap declaration, usages isn't set, and the name and localized name read vibrate.

`// Haptics
new ActionConfig()
{
    name = "haptic",
    localizedName = "Haptic Output",
    type = ActionType.Vibrate,
    usages = new List<string>() { "Haptic" },
    bindings = new List<ActionBinding>()
    {
        new ActionBinding()
    {
    interactionPath = haptic,
    interactionProfileName = profile,
}`
 
I created a custom profile based off the HP & Microsoft profile and added the changes which resulted in functional haptics.

**Comment by yl-msft** [comment]
Thanks for reporting this, and fixes, @Reahreic .  We are looking at this issue.

**Comment by keveleigh** [comment]
@Reahreic, which API are you using to send haptics to the controller? I've tried a couple to try to repro and haven't yet been successful!

**Comment by Reahreic** [comment]
Sorry for the delayed reply, we're using V1.4.4 of Unity's 'new' input module alongside the `UnityEngine.XR.OpenXR.Input` namespace.

We first register a 'Haptic' Input Action of Action Type: Pass Through, and Control Type: Haptic in the editor. Then at runtime once a controller has been detected via the `InputSystem.onDeviceChange` event we call our classes `BindHaptics(inputActions.LeftController.Haptic);` method to cache a reference to the defined 'Haptic' Input Action.

Triggering haptics is done by helper methods that eventually call `OpenXRInput.SendHapticImpulse()` passing in the cached Haptic Input Action and several 'pattern' parameters.

The following excerpt from our controller class is what we use to drive a basic repeating and continuous patterns.
```
using System;
using UnityEngine;
using System.Collections;
using UnityEngine.InputSystem;
using UnityEngine.XR.OpenXR.Input;

public class HPG2ControllerStub {

	public bool supportsHaptic { get; protected set; }
	InputAction hapticAction;

	/* Haptic Feedback */
	/// <summary>
	/// Binds an input system action for use with sending haptic feedback commands to the controller.
	/// </summary>
	/// <param name="hapticAction">The input system action to bind for haptic feedback.</param>
	public void BindHaptics(InputAction hapticAction) {
		this.hapticAction = hapticAction;
		supportsHaptic = true;
	}


	/// <summary>
	/// Pulses the haptic using the specified values for the specified duration.
	/// </summary>
	/// <param name="amplitude">The strength of the pulse. [0-1]</param>
	/// <param name="interval">the period between pulses in seconds. [0-n]s</param>
	/// <param name="pulseDuration">The duration of each individual pulse. [0-n]s</param>
	/// <param name="totalDuration">The total duration of the sequence. [0-n]s</param>
	/// <param name="frequency">The frequency at which the pulse occurs. [0-300]Hz</param>
	public void PulsedHaptic(float amplitude, float interval, float pulseDuration, float totalDuration, float frequency) {
		if(hapticAction == null) {
			Debug.LogWarning("The controller '" + this + "' does not have a bound haptic action!");
			return;
		}

		StartCoroutine(HapticPulseRepeater(amplitude, interval, pulseDuration, totalDuration, frequency));
	}
	IEnumerator HapticPulseRepeater(float amplitude, float interval, float pulseDuration, float totalDuration, float frequency) {
		WaitForSeconds wait = new WaitForSeconds(interval);

		float start = Time.time;
		while(Time.time - start < totalDuration) {
			OpenXRInput.SendHapticImpulse(hapticAction,
					amplitude,
					frequency,
					pulseDuration,
					device);
			yield return wait;
		}
	}

	/// <summary>
	/// Vibrates the haptic system for for the specified duration.
	/// </summary>
	/// <param name="amplitude">Strength of the vibration. [0-1]</param>
	/// <param name="duration">Number of seconds to vibrate for.</param>
	/// <param name="frequency">The frequency at which to pulse [0-300Hz]</param>
	public void ContinuousHaptic(float amplitude, float duration, float frequency) {
		if(hapticAction == null) {
			Debug.LogWarning("The controller '" + this + "' does not have a bound haptic action!");
			return;
		}

		OpenXRInput.SendHapticImpulse(hapticAction,
			amplitude,
			frequency,
			duration,
			device);
	}
}
```

**Comment by keveleigh** [comment]
@Reahreic thanks for the code snippet! I've been able to repro and have a fix pending for the plugin. Thanks for the report!

**Comment by keveleigh** [comment]
@Reahreic I've merged a fix for this into the plugin and it should make the upcoming 1.7.1 release in the new year! Thanks for the report and the detailed writeup on a repro and resolution.
