### ISSUE TITLE
Getting `OnInstanceDestroy, remotingState was Connect` when attempting to initiate holographic remoting connection.

### ISSUE THREAD

**Issue by porter557** [microsoft/OpenXR-Unity-MixedReality-Samples#137]
I am unable to establish a holographic remoting session due to the following error:

```
[AppRemotingPlugin] OnInstanceDestroy, remotingState was Connect.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.OpenXR.Remoting.AppRemotingPlugin:OnInstanceDestroy(UInt64)
UnityEngine.XR.OpenXR.Features.OpenXRFeature:ReceiveNativeEvent(NativeEvent, UInt64)
UnityEngine.XR.OpenXR.OpenXRLoaderBase:ReceiveNativeEvent(NativeEvent, UInt64)
UnityEngine.XR.OpenXR.OpenXRLoaderBase:Internal_DestroySession()
UnityEngine.XR.OpenXR.OpenXRLoaderBase:Deinitialize()
UnityEngine.XR.OpenXR.OpenXRLoaderBase:Initialize()
UnityEngine.XR.Management.<InitializeLoader>d__24:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Microsoft.MixedReality.OpenXR.BasicSample.AppRemotingSample:ConnectToRemote(String)
UnityEngine.Events.UnityAction`1:Invoke(T0)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
```

### Steps to reproduce:
1. Clone this repository
2. Check out the 'main' branch or the branches with tags 'v1.6.0' or 'v1.7.0'. (I get same result on all these versions) (remoting works just fine with tag 'v1.5.0')
3. Run the sample project in `OpenXR-Unity-MixedReality-Samples\RemotingSample\` (i'm using Unity version 2020.3.37f1)
4. Set target platform to 'Universal Windows Platform' and build.
5. In Visual studio, open project and use 'x64' and 'local machine' settings running in debug.
6. Launch the holographic remote player on Hololens 2
7. Type in IP address in the application
8. Press 'connect'
9. You should see the OnInstanceDestroy error from above. No connection is made.

According to this site: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/known-issues
Could this issue still be affecting OpenXR version 1.6 and 1.7?

![image](https://user-images.githubusercontent.com/119343453/211869875-8b645ee0-c9cf-4cf8-8f88-09c3e2fe90a5.png)

Any help is greatly appreciated. Thank you!

**Comment by satyapoojasama** [comment]
Hi @porter557, thank you for reporting the issue. Unfortunately, the issue cannot be reproduced on our end. To double check, may I know if you checked "Holographic Remoting remote app feature group" and unchecked "Initialize XR on Startup" under your Unity project's PlayerSettings-> XR Plug-in Management? 

It would be great if you can attach the log file completely. Also, the above "OnInstanceDestroy" log is not an error but an effect of no connection being established.

**Comment by porter557** [comment]
Thank you for the reply!

Here are the settings/logs you requested.
![image](https://user-images.githubusercontent.com/119343453/212118882-92f2bd25-4615-404c-821e-e0a6e435bd7c.png)
Here is the complete debug runtime log from visual studio:
[debuglog.txt](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/files/10403597/debuglog.txt)

That is a good point about OnInstanceDestroy not being an error haha. I do see XR runtime errors in the log and I will look through it more carefully. If you know where to look that would be great. It was odd that this worked just fine on version 1.4.4 and 1.5 but only when I switched to 1.6 or 1.7 did I have a problem, so I'm not sure why the XR runtime would be unavailable

Thanks again for the help

**Comment by satyapoojasama** [comment]
Hi @porter557, thank you for the logs. This did help us debug the issue a little further. Could you please try and set the following regkey on your PC and then try if remoting works?

- Go to the following path in Registry Editor " HKLM\SOFTWARE\Khronos\OpenXR\1"
- Rightclick on the empty space and click "New"-> "String Value".
- Modify the "Name" to "ActiveRuntime"
- Rightclick on the "ActiveRuntime" and hit "Modify...". 
- Set the "Value data:" to "C:\WINDOWS\system32\MixedRealityRuntime.json"
![image](https://user-images.githubusercontent.com/69484678/212211523-0038013c-b645-49cc-8063-73388159acf4.png)

- Close the editor and run the uwp remoting app again to see if the issue repros.

**Comment by porter557** [comment]
@satyapoojasama,

Thank you! Sorry it's taken a bit to get back to you.

I tried building my project as a windows standalone in Unity, I appear to have the same issue with remoting.

I do not appear to have "Khronos" in my registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos?, which appears to be needed for OpenXR. Not sure how it was working before on previous versions? Do I simply create it or am I lacking an install/dependency? OpenXR is definitely installed with Unity using the mixed reality feature tool.

**Comment by satyapoojasama** [comment]
Hi @porter557, thank you for your response. Installing OpenXR with Unity does not write to registry. Usage of any VR application or using Mixed Reality Portal does. Anyways, if this key doesn't exist, there is an alternative in our plugin code to set a detour key for remoting. Somehow your PC doesn't allow setting a key in HKCU.  It is a bug, usually users need not worry about setting registry keys to use remoting.  I am working on writing a simple C++ application which will give more clarity on why your PC doesn't allow setting a key in HKCU. Will share it soon. It would be really helpful for us to debug what is going on if you could report us back with the results.

Also, in the previous versions of our plugin, remoting runtime is set using environment variables. This behavior is changed to using regkey instead after 1.5. That is why you might be observing this issue now.

**Comment by porter557** [comment]
Hi @satyapoojasama. I unfortunately cannot send you dxidag or allow external custom code to run in my environment. I have contacted my team to help me figure out why this issue is happening as it is most likely due to our our managed environment.
I will update the issue here once it is resolved or If I have more questions :)

Thank you very much for your help in pointing me in the right direction!

**Comment by satyapoojasama** [comment]
Hi @porter557. It is unfortunate that this is the case, but it is totally understandable. I will be closing this issue for now. Although, we will be working on a better and a more robust solution to this problem meanwhile. Once the patch is ready, I will make sure to communicate it with you here. It would be wonderful if you could validate it later and confirm it works. Thank you once again for reporting us about this issue.

**Comment by porter557** [comment]
Update for anyone else experiencing this problem.

I was able to get this working by installing "OpenXR for Windows Mixed Reality" through the microsoft store. And setting it as the default OpenXR runtime in the "OpenXR Tools for Windows Mixed Reality" microsoft store app.

I am still a bit confused as to how the older version (1.4.4) of the plugin was working without having a specific runtime installed. But it could be that my managed environment wasn't allowing unity to set registry but it allowed a microsoft store app to do so.

Either way, the code works great with this installed and I can continue to develop my application using the latest 1.7 version.

Thanks again for the help.

Cheers!

**Comment by mbucchia-msft** [comment]
@porter557, by installing the OpenXR for WMR package, you effectively created the registry we asked you to try with in our earlier message:

> I do not appear to have "Khronos" in my registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos?, which appears to be needed for OpenXR. Not sure how it was working before on previous versions? Do I simply create it or am I lacking an install/dependency? OpenXR is definitely installed with Unity using the mixed reality feature tool.

This is why that solved your issue. Those instructions [here](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/137#issuecomment-1381166738) would have likely solved your problem even without needing to install OpenXR for WMR.

> I am still a bit confused as to how the older version (1.4.4) of the plugin was working without having a specific runtime installed.

See @satyapoojasama's reply:

> It is a bug, usually users need not worry about setting registry keys to use remoting.

For some reason, your system's permissions did not allow our code in Unity to create the necessary registry keys to let you use remoting in spite of not having the registry key already existing.
