### ISSUE TITLE
Invoking SkinnedMeshRenderer.BakeMesh() with tracked hand mesh in HoloLens 2 is creating an invalid mesh with OpenXR.

### ISSUE THREAD

**Issue by krishx007** [microsoft/OpenXR-Unity-MixedReality-Samples#140]
**----Bug----**
Invoking SkinnedMeshRenderer.BakeMesh() with tracked hand mesh in HoloLens 2 is creating an invalid mesh.  Rather than creating  a mesh which represent the current deformation of the hand mesh, it is creating a mesh that contains the outdated deformed mesh. We have noticed the outdated deformation is most likely represents the hand state when the HoloLens first recognized the tracked hands in its field of view (FOV) .
It is happening with MRTK version 2.8.2 and with latest version of Unity 2020.3.x and Unity 2021.3.x

**------To reproduce------**
1)Open the "BasicSample" unity project with the latest version of Unity 2020. (We used Unity 2020.3.43)
https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/BasicSample

Use the MRTK (Foundation & StandardAssets packages) and Mixed Reality OpenXR plugins version 2.8.2

3)Now attach some script to "RiggedHandLeft" or "RiggedHandRight" prefab which will capture the mesh of the SkinnedMeshRenderer component associated with the tracked hand prefab.

You can try using this mono script, just attach it to "RiggedHandLeft" or "RiggedHandRight" prefab and trigger "BakeMesh()" when the hand is tracking in HoloLens 2.
https://gist.github.com/krishx007/a645f77c1284b2f69479da8e3266fce1

**---------Expected behavior----------**
Invoking SkinnedMeshRenderer.BakeMesh() with tracked hand mesh in HoloLens 2 should generate a mesh geometry similar to the current deformation of the hand mesh at the exact same position where the tracked hand mesh was visible.

**Comment by krishx007** [comment]
Could any of the contributor please have look at this. Our project progress has been stalled because of this bug.

**Comment by marlenaklein-msft** [comment]
This may be relevant to the workaround in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11399.

**Comment by AMollis** [comment]
@krishx007 , please reach out if this is still an issue.   Open a new issue if needed.

@marlenaklein-msft has provided a possible workaround.
