### ISSUE TITLE
Unity LogError: "ConnectToPlayer is not supported, enable App Remoting feature to use this."

### ISSUE THREAD

**Issue by MebilyChen** [microsoft/OpenXR-Unity-MixedReality-Samples#146]
Hello! 
I'm new to this field and when I was testing this Remoting function I always run into this **"ConnectToPlayer is not supported, enable App Remoting feature to use this."** error and I don't know how to solve it. I followed the instruction [here](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/use-pc-resources) and find the sample successfully connected to my HL2, but when I try to build this function into my own project (by dragging the prefabs into the scene), it didn't work. I definitely checked these two options:
![](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/images/039-select-holo-remoting.png)
Here is the information regarding the RemotingSampleScene which can connect HL2 successfully on my pc:
![remotingSample](https://user-images.githubusercontent.com/71856534/229595579-bbde839e-4cff-4e57-a1fa-c5e24c7e8557.png)
And here is the information regarding my own project:
![myproject](https://user-images.githubusercontent.com/71856534/229595896-29b29986-019b-4422-bf4b-685d60ec7dab.png)
I noticed that in my project there is no “OpenXR Runtime”， but I don't know why and how or does it have anything to do with my error.
I also checked the code but since I know so little about programming I can't possibly tell the problem.
![code](https://user-images.githubusercontent.com/71856534/229598336-b1ddd8af-2926-4824-bf97-9100becbe8c5.png)
Did I miss something? I think maybe it's just a minor "project settings" problem but I'm not sure and don't know where to look at. 
If you need more details, please tell me and I will try to provide more information. 
Thanks in advance!

**Comment by MebilyChen** [comment]
I'm terribly sorry! I checked again and found out I didn't check the two boxes under the PC standalone tab but only under the UWP.
But I'm getting a new error now: **[AppRemotingPlugin] OnInstanceDestroy, remotingState was Connect.**
Any suggestions? I will keep looking for solutions.

**Comment by yl-msft** [comment]
@MebilyChen , glad you found the issue in your app.  App remoting is typically applicable to standalone project settings since that's how the app is typically built.

The "OnInstanceDestroy, remotingState was Connect" is not an error.  It's a normal log and just for your information.  There's no need to "fix" it.
