### ISSUE TITLE
How to use XRAnchorTransferBatch.ImportAsync(Stream) on Hololens 2

### ISSUE THREAD

**Issue by ChasingD** [microsoft/OpenXR-Unity-MixedReality-Samples#149]
openxr version 1.8.0
I use XRAnchorTransferBatch to export anchors, but when I import anchors using XRAnchorTransferBatch.ImportAsync(Stream), null is returned.

> Stream stream = new MemoryStream(anchorData);
	stream.Seek(0, SeekOrigin.Begin);
	var transferBatch = await XRAnchorTransferBatch.ImportAsync(stream);

        
anchorData is byte[] transfered.
result: transferBatch  is null

**Comment by ChasingD** [comment]
> public static async Task<XRAnchorTransferBatch> ImportAsync(Stream inputStream)
		{
			AnchorTransferBatch anchorTransfer = new AnchorTransferBatch();
			SerializationCompletionReason num = await anchorTransfer.ImportAsync(inputStream);

			if (num == SerializationCompletionReason.Succeeded)
			{
				return new XRAnchorTransferBatch(anchorTransfer);
			}

			return null;
		}
Result: SerializationCompletionReason is UnknownError

**Comment by WikkidEdd** [comment]
Presumably, you're transferring the anchor data over a network connection or something? Have you confirmed that the anchorData isn't being transformed somehow as part of the transfer process? i.e checking the size and doing a checksum on the byte array.

**Comment by ChasingD** [comment]
> Presumably, you're transferring the anchor data over a network connection or something? Have you confirmed that the anchorData isn't being transformed somehow as part of the transfer process? i.e checking the size and doing a checksum on the byte array.

Hi WikkidEdd, thanks for your reply. 
I found the problem inspired by you.
The problem is the anchor data is wrong during the export phase. So the data imported is wrong.

**Comment by AMollis** [comment]
@ChasingD is there still an issue here?  From your last comment, sounds like you discovered an issue with the exported data.

> The problem is the anchor data is wrong during the export phase. So the data imported is wrong.

Also, if there is still an issue, are you able to provide a Unity project with an isolated reproduction of the issue?   This will help expediate the investigation on our side.

If you are just in need of API assistance, you can follow-up with our support via https://aka.ms/mrsupport.  In this case, you would select help with "Immersive Headset Programming", concerning an "API" and "Spatial Anchors" issue.

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/36461279/593e7bd8-bf3c-4f31-b1de-758bbfeb2f17)

**Comment by Mirgiacomo** [comment]
Hi @ChasingD ,
I'm working on something similar but I'm having problems with the export phase of the anchors (I want export anchors on a database)
Can you provide me the piece of code/function that does the export? and the import?

Thanks
