### ISSUE TITLE
Removed Android related XR features for hand tracking and controller models breaks MRTK2

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/OpenXR-Unity-MixedReality-Samples#150]
"Removed Android related XR features for hand tracking and controller models.
Recommend using the OpenXR plugin from Unity and Meta for these features."

A lot of projects now run on MRTK2 and they work pretty much fine on Quest 2/Pro. This will break those projects! Why break something that works?

**Comment by meta-meta** [comment]
> Recommend using the OpenXR plugin from Unity and Meta for these features.

What does this mean exactly? On Quest 2/Pro would hand tracking and controller models need to be implemented outside of MRTK? What happens to hand rays in that case?

**Comment by KBonds** [comment]
Hello all,

We've heard feedback from multiple sources about the inconvenience of removing Android hand tracking support - the team is working on adding this feature back into the upcoming 1.8.1 release, so stay tuned.

When we re-enable this, hand tracking on Android will now be deprecated, but no longer removed. We still encourage projects to transition to [Unity's com.unity.xr.hands package](https://docs.unity3d.com/Packages/com.unity.xr.hands@1.2/manual/index.html) for Android hand tracking.

**Comment by KBonds** [comment]
We've just released version 1.8.1, which includes the (deprecated) restoration of Android hand tracking support!

We're hoping this helps y'all and others make the transition more smoothly to packages like [Unity's com.unity.xr.hands package](https://docs.unity3d.com/Packages/com.unity.xr.hands@1.2/manual/index.html) for use with Android.

**Comment by LocalJoost** [comment]
Good show! Thanks!
