### ISSUE TITLE
ARAnchorManager.anchorsChanged updated event receives the ARAnchors that has been removed from the ARAnchorManager.subsytem

### ISSUE THREAD

**Issue by hemasree99s** [microsoft/OpenXR-Unity-MixedReality-Samples#152]
I am using OpenXR 1.3 version. I am removing a ARAnchor through ArAnchorManager.subsystem.TryRemoveAnchor(trackableId) which returns true. But the ARAnchorManager.anchorsChanged updated event receives the ARAnchor that has been removed

**Comment by devdeeprc** [comment]
@hemasree99s couple of questions:
1. When you say OpenXR 1.3 version, do you mean it for com.microsoft.mixedreality.openxr or com.unity.xr.openxr? For either package, we have newer versions available. 1.8 for com.microsoft.mixedreality.openxr and 1.7 for com.unity.xr.openxr. Does this repro for those versions as well?
2.  Does this happen everytime you remove and anchor or does it only happen sometimes?

**Comment by KBonds** [comment]
Please update to the lastest version of the OpenXR plugin and let us know if you can still repro this issue!
