### ISSUE TITLE
AppRemoting: DisconnectReason not getting reported

### ISSUE THREAD

**Issue by zenorbi** [microsoft/OpenXR-Unity-MixedReality-Samples#153]
We are using the `AppRemoting.StartConnectingToPlayer` to connect Unity to Hololens but when there is an error the `AppRemoting.Disconnecting` always reports `DisconnectReason.None`.

I believe the issue is that `AppRemotingSubsystem.OnSessionLossPending` calls `TryGetConnectionState` and thus "consumes" the disconnect reason, so when later the `AppRemotingSubsystem.ConnectRoutine` calls `TryGetConnectionState` it doesn't get the reason.

I have verified this with a debugger. The `AppRemotingSubsystem.OnSessionLossPending` does get the correct disconnect reason.

**Comment by yl-msft** [comment]
Thanks for reporting.  I'm pinging back to the feature team to investigate this issue.

**Comment by satyapoojasama** [comment]
Hi @zenorbi,

Unfortunately, I am unable to repro this issue on the latest BasicSample in this repo. Can you provide more details on what kind of error you are referring to before disconnecting? 

Also, I am not sure how using "TryGetConnectionState" twice will hinder getting disconnecting reason. Could you please share some Unity Player Log for us to debug further?

**Comment by zenorbi** [comment]
Hi @satyapoojasama,

Thank you for looking into this. I cloned this repo and opened the `RemotingSample` project in Unity 2020.3.43f1 as indicated by the ProjectVersion.txt. All I did is that I added `Debug.Log($"DISCONNECT REASON: {disconnectReason}");` to this method: https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/blob/666f809b418b8c84fd17e5d00589708c014d76a6/SampleShared/Samples/AppRemoting/Scripts/AppRemotingSample.cs#L234

I then entered play mode and tried to connect to an unused IP address. The log I received was:

```
DISCONNECT REASON: None
```

[Editor.log](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/files/11610584/Editor.log)

I would expect a `HandshakeUnreachable`, the same as what the `AppRemotingSubsystem` receives.

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/313625/179d6050-6cb5-417b-a26c-0382475922ea)

Interestingly if I build this project, I never even receive an `OnDisconnecting` callback in the player.

**Comment by zenorbi** [comment]
Here is a video where I reproduce this issue on a fresh git clone:

https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/313625/451c3d9a-07c6-443f-9175-9fa79d57bc1e

**Comment by satyapoojasama** [comment]
Hi @zenorbi , we fixed this issue and it will be available in the next release of our plugin. Thank you.

**Comment by satyapoojasama** [comment]
1.9 release is now out. Please update to get the fix for this bug.
