### ISSUE TITLE
AzureSpatialAnchorsSample - Anchors recognized only in the same app session

### ISSUE THREAD

**Issue by PowZone** [microsoft/OpenXR-Unity-MixedReality-Samples#156]
Unity 2021.3.14f1 + MRTK 2.8.3 on Hololens 2

I'm testing this example, azure sessions works and anchors are created and recognized between different azure sessions.
But if I kill the app and run it again no anchor is found.

I need to be able to reload all anchors and share them with other devices.

I just configured azure credentials in the spatial anchor manager component.

Am I forgetting some setting?

thank you!

**Comment by yl-msft** [comment]
@PowZone , please report this to Azure Spatial Anchor team for cross session anchor persist.  https://github.com/Azure/azure-spatial-anchors-samples  Thanks.

**Comment by AMollis** [comment]
@PowZone , I'm closing this issue.  Please open an issue at https://github.com/Azure/azure-spatial-anchors-samples if this is still a problem.
