### ISSUE TITLE
cannot run the four demos of ARAnchor, ARRaycast, ARPlane, and ARMesh demo

### ISSUE THREAD

**Issue by oneSitDown** [microsoft/OpenXR-Unity-MixedReality-Samples#176]
I cannot run the four demos of ARAnchor, ARRaycast, ARPlane, and ARMesh on Hololens2 or mobile phone. 
Can you provide a detailed tutorial? I packaged these four scenes directly and couldn't even open the camera, 
and there were no errors.

**Comment by marlenaklein-msft** [comment]
Hi @oneSitDown,

The ARAnchor, ARRaycast, ARPlane, and ARMesh scenes are all meant to be run with the SharedSubscene. The camera is located in the SharedSubscene under the XRRig. It should look something like this in editor:

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/125413876/c6f3c09b-ab1a-43d9-bc15-8700fad28c0f)

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/125413876/aad914bf-848c-45c7-bd59-65801de6f8a5)

The way the sample is set up by default, all of the scenes are built, with the SharedSubscene at index 0. You start in the menu scene, and can then navigate to all of the others. (And SharedSubscene is always there providing the XRRig and MixedRealityToolkit)

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/125413876/05e72c5a-7eb7-49a3-9d2f-2e3d6179644e)

You should be able to:

1) Clone the repo and open in Unity editor.
2) Fix any project validation for OpenXR (Mixed Reality -> Project Validation Settings -> Select Your Platform and then resolve any issues in Project Settings -> XR Plugin Management -> OpenXR)
3) Confirm that your list of scenes in build settings matches the above.
4) Build and deploy - you should see the Main Menu and can navigate to ARAnchor etc.

If you want to build these scenes on their own, you would need to make some changes. IE Add all the necessary stuff from SharedSubscene into the scene you want to build on its own.

**Comment by oneSitDown** [comment]
Can I think so, our openxr sdk. Just called the method of AR Foudation and did not pass the dof data to AR Foudation?

**Comment by oneSitDown** [comment]
And SharedSubscene has nothing to do with the entire demo, right? Will this part of the demo be removed in the future? This function is obviously redundant for the demo

**Comment by marlenaklein-msft** [comment]
Hi @oneSitDown, what behavior are you seeing on HoloLens2?

Is 'Initialize XR on Startup' enabled in OpenXR project settings?

**Comment by oneSitDown** [comment]
I actually want to run these demos on Android phones instead of running these demos on Hololens 2. I have enabled Initialize XR on Startup'. Other demos can run normally. These few demos cannot be run. Can these AR Foudation demos be run on mobile phones? Can they only be run on Hololens2? If it doesn’t work on my phone, I won’t try it.

**Comment by oneSitDown** [comment]
Is there any tutorial on how to run ARAnchor, ARRaycast, ARPlane, and ARMesh on mobile phones?
![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/47908151/6a35148a-4ded-4c6e-8d43-5a9a1b6b5ac9)
Does ARcore have to be enabled?

**Comment by AMollis** [comment]
@oneSitDown we only support HoloLens for this project.  If you need help setting up this project on HoloLens, please open a support ticket @ https://aka.ms/hldevsupport

It's recommended to run these samples on HoloLens 2 using the following versions:

- Latest Visual Studio 2022
- Latest Unity 2021.3 LTS. Please double check [the Unity's blocking bugs for HoloLens 2](https://aka.ms/openxr-unity-blocking).
- Latest Unity OpenXR plugin, recommended 1.3.1 or newer.
- Latest Mixed Reality OpenXR Plugin, recommended 1.4.0 or newer. Please [follow the latest release notes](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases).
- Latest MRTK-Unity, recommended 2.7.3 or newer.
- Latest OpenXR Runtime, recommended 109 or newer.

If there is a bug on HoloLens, can you please provide the following information:

- Visual Studio version
- Unity Version
- Unity OpenXR Plugin version
- Microsoft Mixed Reality OpenXR Plugin version
- MRTK2 version
- Hololen's OS version

**Comment by oneSitDown** [comment]
Okay, I thought you were compatible with Android-related logic, so I connected to AR Foudation. I’ll try the Hololens-related functions again.
