### ISSUE TITLE
Missing Hand Ray in Unity Mixed Reality Template - Aim Position/Rotation/Flags

### ISSUE THREAD

**Issue by camnewnham** [microsoft/OpenXR-Unity-MixedReality-Samples#179]
I have been testing cross-platform with the [Unity MR template ](https://docs.unity3d.com/Packages/com.unity.template.mixed-reality@1.0/manual/index.html) in Unity 2022.3.21f1 with Microsoft.MixedReality.OpenXR 1.9.0. 

When building with the meta openxr plugin and targeting quest pro, this works as expected. 

On HoloLens2, hands track correctly but hand rays do not appear. This appears to be because the values for the Ray interactor pose refer to Aim Position and Aim Rotation, which are present in the [Meta OpenXR plugin](https://docs.unity3d.com/Packages/com.unity.xr.hands@1.3/manual/features/metahandtrackingaim.html). 

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/19278856/e980e27c-e2eb-4d01-a4f3-92bc912c2ade)

Setting these values to use a fallback XR Hand Device Position and Rotation (or explicitly to HoloLens equivalents) works-ish, but I'm unsure as to whether these are the "correct" poses. 

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/19278856/4136e616-5e5f-4cba-8faa-7c416e636d96)

In this template project it also does not correctly disable/re-enable the pointer after hand tracking is lost/regained, which appears to be due to the flags which are again provided by the Meta plugin and used to switch between poke/direct/ray interactors:

![image](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/assets/19278856/073c449e-1c07-4f2a-b738-4cbed4cdcabf)

MRTK also had a separate [InteractionModeManager ](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/blob/main/org.mixedrealitytoolkit.input/InteractionModes/InteractionModeManager.cs) which seemed to have the same goal.

So my queries are:
1. How should I be specifying "Aim" position and rotation? Is this something the Microsoft OpenXR plugin can provide?
2. Is there an equivalent to the "Flags" I can use to determine when I should be using Poke, Direct or Ray interactors?

Unity also don't have issues [on their sample github](https://github.com/Unity-Technologies/mr-example-meta-openxr), otherwise I'd also report this there.

**Comment by AMollis** [comment]
@camnewnham, this appears to be a Unity XRI question.    MR Plugin itself doesn't implement XR Interaction Toolkit functionality. 

Can you please open a bug/issue with Unity? https://support.unity.com/hc/en-us.

We recommend utilizing MRTK3 if you want XRI components targeting HoloLens 2.

**Comment by AMollis** [comment]
@camnewnham , also if you have hololens 2 development questions, please reach out to our support team @ https://aka.ms/hldevsupport

**Comment by camnewnham** [comment]
Thanks. I had thought it was the OpenXR plugin provider that would provide the bindings, which are then consumed by XRI.
I've made a [topic on Unity Discussions](https://discussions.unity.com/t/unity-mixed-reality-template-misconfigured-for-hololens-2/347533) for it.
