### ISSUE TITLE
Missleading warning `"Run in Background" is not necessary in this version of Unity...`

### ISSUE THREAD

**Issue by anonymous2585** [microsoft/OpenXR-Unity-MixedReality-Samples#184]
The warning `"Run in Background" is not necessary in this version of Unity and can add unwanted performance costs for XR Unity apps.` is missleading.

We have one usecase that require "Run in Background" to be activated: when an other 2D UWP panel application is open inside the 3D app. Without "Run in Background" checked, the Unity app stops rendering and tracking but is still visible by the user (big motion sickness in VR).

Because I had this warning, I disabled "Run in Background", causing this regression we catch only later.

### Fix proposed

Remove this warning or add an "ignore" option that is saved in the project.

**Comment by marlenaklein-msft** [comment]
@anonymous2585 thank you for your feedback. Unfortunately, at this time, this issue does not meet our prioritization bar and will not be addressed. We will let you know if this changes in the future.

If you have additional questions or concerns, you can reply to this issue or open a case with our support team at https://aka.ms/hldevsupport.
