### ISSUE TITLE
XRAnchorTransferBatch  uses deprecated API (SpatialAnchorTransferManager) under the hood

### ISSUE THREAD

**Issue by WikkidEdd** [microsoft/OpenXR-Unity-MixedReality-Samples#186]
With ASA being retired at the end of the year and no replacement in sight, we're looking for other viable options. Our app only requires a single anchor to be shared between participants of a multiuser session to put all the devices in a shared reference frame. The XRAnchorTransferBatch looks like it would be a suitable replacement for ASA for our use case.

However, it makes us a little uneasy that the XRAnchorTransferBatch (which isn't marked as deprecated or retiring soon) is using SpatialAnchorTransferManager internally and using `#pragma warning disable CS0618` to hide the warnings about SpatialAnchorTransferManager being deprecated.

There are references to this API being [deprecated as far back as 2018](https://github.com/MicrosoftDocs/winrt-api/issues/425) in favour of an API that never actually got enabled. Also, a reference by @yl-msft on the [non-Unity OpenXR repo](https://github.com/microsoft/OpenXR-MixedReality/issues/99#issuecomment-1010648363) that this is a deprecated API and that we should use ASA.

I would imagine there are many developers looking for ASA alternatives right now. XRAnchorTransferBatch would appear on the face of it to be the best alternative, but if it's secretly using a deprecated API then it could lead people to spend time and effort implementing it only to have that feature be made fully obsolete in the future. 

Given all of the above, it would be very useful if the maintainers of this repo could either:
1. Make it clear that XRAnchorTransferBatch is using a deprecated API so that everyone has that visibility without having to look at the source code.
or
2. Speak to the platform team and get SpatialAnchorTransferManager un-deprecated (it's been working for 6 years while deprecated) in order to give developers the confidence to use it.

2 would be the ideal given it is the only reasonable ASA alternative on the horizon.

**Comment by dudziakl** [comment]
Here is Microsoft's reply that I have received asking for the ASA replacement. It doesn't explain anything yet but it is better than nothing. 
> We have been working on the next generation of spatial computing platform that is presently in Private Preview (PrP). This platform offers a broader and more robust set of spatial computing capabilities and is the successor for both ASA and AOA. We can only share more information about the next generation of spatial computing platform under NDA. Please note that we are presently updating our roadmap, MVP and GTM plans. We aim to complete this exercise by mid 2024 and will share more information at that time.

**Comment by WikkidEdd** [comment]
We have the same information regarding the ASA replacement. The language used implies that they will have only completed their _plans_ by mid 2024, not have a solution to offer by then. Given the retirement is happening in November, it seems very unlikely they will have a GA release by the time the old system retires.

I'm sticking by my original statement ;) 
> With ASA being retired at the end of the year and **no replacement in sight**, we're looking for other viable options

**Comment by AMollis** [comment]
Hi @WikkidEdd , thank you for your issue.

We are currently investigating and will reply with guidance once the investigation has completed.  Thank you for patience.

**Comment by AMollis** [comment]
@WikkidEdd ,

This [XRAnchorTransferBatch](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.openxr.xranchortransferbatch?view=mixedreality-openxr-plugin-1.10) Mixed Reality Plugin API was originally introduced to assist HoloLens 2 Unity applications moving to newer versions of Unity and does rely on [SpatialAnchorTransferManager](https://learn.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialanchortransfermanager?view=winrt-22621) API.

Currently there are no plans to remove [SpatialAnchorTransferManager](https://learn.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialanchortransfermanager?view=winrt-22621) API. If this API is removed in future, it will be communicated in advance. Given this I will be closing this bug as having no action.

Thank you for your issue. If you have additional questions or concerns, you can reply to this issue or open a case with our support team at https://aka.ms/hldevsupport
