### ISSUE TITLE
[Feature Request] Support saving and loading using the ARAnchorManager API

### ISSUE THREAD

**Issue by camnewnham** [microsoft/OpenXR-Unity-MixedReality-Samples#187]
At present, it appears that the technique for saving anchors on the HoloLens 2 is to use `Microsoft.MixedReality.OpenXR.XRAnchorStore`.  I was lucky to find an example of this usage in the World Locking Tools samples.

However there are similar functions in the `ARAnchorManager` API that would not require a whole lot of `#if UNITY_WSA` -- enabling code compatibility with Meta etc.

At present, `ARAnchorManager.subsystem.subsystemDescriptor.supportsSaveAnchor` returns false, so it appears this API is not yet implemented. Is this on the roadmap for the Microsoft OpenXR plugin?

**Comment by AMollis** [comment]
@camnewnham thank you for your feedback. The team will prioritize accordingly.  For the time being please continue to use `Microsoft.MixedReality.OpenXR.XRAnchorStore`.
