### ISSUE TITLE
Locally persistent anchor requests (such as API for WorldAnchorStore in Unity 2019) 

### ISSUE THREAD

**Issue by zhangtianhong-1998** [microsoft/OpenXR-Unity-MixedReality-Samples#189]
Regarding locally persistent anchor requests, I noticed that older versions of Unity included WorldAnchorStore to provide a solution for locally persisting anchors. However, this 2019 version of Unity has been dropped, and MRTK3 does not support older versions of Unity. In practice, due to application requirements, some scenarios are that the public network is disconnected or the public network is not allowed to access.

This created a big obstacle for us in MRTK3 English, and I asked the development team to reconsider the feasibility of locally persistence anchor requests for MRTK3 supplement

**Comment by marlenaklein-msft** [comment]
@zhangtianhong-1998 The MR Plugin includes an [XRAnchorStore](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.openxr.xranchorstore?view=mixedreality-openxr-plugin-1.11) API for local anchor persistance, an example of how to use this can be found in the [BasicSample](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/BasicSample) in the ARAnchor scene. The MR Plugin can also be used with an MRTK3 project. If you have additional questions or concerns, you can reply to this issue or open a case with our support team at https://aka.ms/hldevsupport.
