### ISSUE TITLE
Can't build for HoloLens 2 cause of a FileNotFoundException

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/OpenXR-Unity-MixedReality-Samples#40]
Hi,

I'm looking for testing the OpenXR HoloLens samples you did but I m facing a FileNotFoundException : 
"FileNotFoundException: Packages/com.microsoft.mixedreality.openxr/Runtime/universalwindows/x64/MicrosoftOpenXRPlugin.dll does not exist"

This is the first time I open this project and I didn't made any change on.

Unity version : 2020.3.13f1

**Comment by yl-msft** [comment]
@Kent1LG ,  Did you installed git LFS before cloning this repo?

> NOTE: This repository uses Git Large File Storage to store large files, such as Unity packages and images. Please install the latest git-lfs before cloning this repo.

**Comment by yl-msft** [comment]
@Kent1LG  I hope you get pass this issue by using git LFS before cloning this git repo.  Let us know if you have further questions.

**Comment by Kent1LG** [comment]
Hello,

Sorry, I didn't keep you in touch.
I did finally succeed, but I don't remember if this was thanks to the git LFS way.
Anyway, thank you very much for your help.
