### ISSUE TITLE
Can't persist anchors in editor playmode

### ISSUE THREAD

**Issue by lmaxsmith** [microsoft/OpenXR-Unity-MixedReality-Samples#44]
It would help a lot as I develop off of this to reduce iteration time if I could use the holographic remoting for play mode. When I do, I get the warning at 
AnchorsSample:54 "XRAnchorStore not available, sample anchor persistence functionality will not be enabled." 
and the related warning at 
AnchorStore:35 "LoadAnchorStoreAsync: The anchor store is not supported; either the feature is not enabled, or the related OpenXR extensions are not supported". 

Is there a setup issue that can make this work?

**Comment by yl-msft** [comment]
@lmaxsmith Thanks for the feedback.  This is a feature that our remoting team is working on.  This is depending on a new OpenXR extension recently published in 1.0.18 SDK, and it's so far only enabled when running the app on HoloLens2 device.  The holographic remoting is already working on this and will be available in future releases coming soon.

**Comment by lmaxsmith** [comment]
Good to know. Thanks. Do we know which version it will be?

**Comment by yl-msft** [comment]
@lmaxsmith ,  the latest version of MR openxr plugin and remoting openxr runtime already supported this.   Could you try it with the latest version?    You can also monitor the latest release notes from this link: https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases

Closing this issue as fixed.
