### ISSUE TITLE
Compatibility Issue with UnityEngine.Windows.Speech namespace ?

### ISSUE THREAD

**Issue by jasonhbartlett** [microsoft/OpenXR-Unity-MixedReality-Samples#47]
Hello, I'm posting this in a few places as I'm not sure exactly who is the culprit for this issue.

I'm making a VR training app and the target platform is Standalone>Windows. I'm using Unity 2020.3 and OpenXR. See below for specific versions.

I have a script that uses the UnityEngine.Windows.Speech namespace that lets me subscribe to the PhraseRecognizedDelegate OnPhraseRecognized event. ( this API is part of the UnityEngine.CoreModule.dll )

My Issue: Everything works great EXCEPT when I have WMR headset connected and the WMR Portal running with Mixed Reality OpenXR runtime.

I have tested that my voice commands DO work fine when running in editor (without WMR headset attached), as a built .exe (again without WMR headset attached), AND even works with Oculus Quest (via Link and the Oculus OpenXR runtime.)

My voice commands DO NOT work with either HP Reverb G1 or G2 and running the WMR portal and the Mixed Reality OpenXR runtime.

I have verified that the microphone device is working as I created a simple echo script that plays what the microphone hears back to me.

As another data point I have an older VR project that I built with Unity 2019.4 with the same target but that uses the Windows Mixed Reality plugin (not OpenXR). The voice commands DO work fine in that app.

So this kinda points me to some problem with the Mixed Reality OpenXR runtime as being compatible with the UnityEngine.CoreModule.dll and specifically with the UnityEngine.Windows.Speech namespace.

Any help with this would be appreciated. Thank you!

SW Versions:
Windows 11 Pro
Unity 2020.3.16
WMR Runtime 107.2109.10010
Packages Include:
XR Plugin Management 4.07
XR Interaction Toolkit 1.0.0-pre.5
OpenXR Plugin 1.2.8
Microsoft Plugins:
Mixed Reality OpenXR Plugin 1.0.2
Mixed Reality Input 0.9.2006
Microsoft Spatializer 1.0.196

**Comment by yl-msft** [comment]
@jasonhbartlett Thanks for the report.  The openxr plugin to unity doesn't interact with speech input APIs.  That said, we can help to route this problem to the experts in this area to diagnose.  Next step, it would be nice to get the unity project that shows the bug, so we can report to the speech team with more precision.  A unity trace logging can also help.

**Comment by jasonhbartlett** [comment]
@yl-msft It's very easy to reproduce this issue:
1. Make new 2020.3.16 Unity project
2. Enable preview packages in project settings
3. Enable XR Plugin Mgmt
4.a. Enable OpenXR
4.b. Add the Microsoft Motion Controller Profile to the OpenXR interaction profiles
5. Add XR Interaction Toolkit package (this is the preview package)
6. Create new empty scene
7. Convert main camera to XR rig
8. Added a floor and cube
9. Create new script (below) and add to the cube
10. Add 3 elements to the string array ("Green", "Blue", "Purple")

(Note: MS plugins mentioned above not necessarry to reproduce this issue)

TEST: If WMR headset IS NOT connected and WMR portal IS NOT running
RESULT: The cube changes color when one of the color names is spoken

TEST: If WMR headset IS connected and WMR portal IS running
RESULT: Nothing happens when the color names are spoken

If needed I've zipped and stuck the Unity project folder on my google drive here: [SpeechCommandIssue](https://drive.google.com/drive/folders/1aNGArT5_PhMT5ygNTK9pG7sgWklphOZ6?usp=sharing)

I've also added the stack trace logs in that folder. One log shows the results WITH the WMR headset and one WITHOUT. I've looked at these but did see anything except to note that no keywords recognized logs appear in the latter.

```csharp
using System;
using System.Text;
using UnityEngine;
using UnityEngine.Windows.Speech;

public class VoiceCommandTest : MonoBehaviour
{
    [SerializeField]
    private string[] m_Keywords;

    private KeywordRecognizer m_Recognizer;
    private Renderer rend;

    void Start()
    {
        //Get the component for the material
        rend = GetComponent<Renderer>();

        //KeywordRecognizer
        m_Recognizer = new KeywordRecognizer(m_Keywords);

        //I dont know what this does
        m_Recognizer.OnPhraseRecognized += OnPhraseRecognized;

        //Start listening
        m_Recognizer.Start();
    }

    private void OnPhraseRecognized(PhraseRecognizedEventArgs args)
    {
        //Log stuff
        StringBuilder builder = new StringBuilder();
        builder.AppendFormat("{0} ({1}){2}", args.text, args.confidence, Environment.NewLine);
        builder.AppendFormat("\tTimestamp: {0}{1}", args.phraseStartTime, Environment.NewLine);
        builder.AppendFormat("\tDuration: {0} seconds{1}", args.phraseDuration.TotalSeconds, Environment.NewLine);
        Debug.Log(builder.ToString());

        //See what the KeywordRecognizer Recognized
        if (args.text.Equals("Green"))
        {
            this.rend.material.color = Color.green;
        }
        else if (args.text.Equals("Blue"))
        {
            this.rend.material.color = Color.blue;
        }
        else if (args.text.Equals("Purple"))
        {
            this.rend.material.color = Color.magenta;
        }
    }
}
`

Please let me know if I can continue to help troubleshoot this issue and I'll do whatever I can. Would be great to know initially if you can reproduce this issue.  Thanks!

**Comment by yl-msft** [comment]
@jasonhbartlett ,  in the latest main branch of this sample repo, we published a new sample to test the speech feature on HoloLens 2.   You can find the sample using "BasicSample" project, and here's [the source of the sample scripts.](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/blob/main/SampleShared/Samples/Speech/Scripts/SpeechSample.cs)  It's similar to what you are showing.   This sample worked fine in our tests.  I wonder if you can try this out and see if this works for you?

![image](https://user-images.githubusercontent.com/33265158/200082152-5bc096e5-674e-42f5-acbe-65ffd4d65f15.png)
