### ISSUE TITLE
dwm.exe crashes and restarts when activating depth debug overlay from Device Portal

### ISSUE THREAD

**Issue by Holo-Krzysztof** [microsoft/OpenXR-Unity-MixedReality-Samples#50]
When running an OpenXR app on HoloLens 2 and activating the hologram stability debug visualization from Device Portal, the app itself and dwm crash. This makes debugging hologram stability on OpenXR impossible.
Any other app that uses HolographicSpace is fine, I tested it with the now deprecated Unity Windows XR plugin.

HoloLens OS version: 20348.1018
Unity 2020.3.17
Unity OpenXR plugin: 1.2.8
Microsoft OpenXR plugin: 1.0.3
OpenXR runtime: 107.2109.10010.0

**Comment by WikkidEdd** [comment]
This issue reproduces 100% for me too.

**Comment by yl-msft** [comment]
This feature is unfortunately not supporting a D3D12 app from HL2 platform, and openxr runtime happens to be a "d3d12" app from the HL2 OS point of view, even if the Unity app itself is still using d3d11 APIs.   We've notified OS rendering team on this feature's limitation.  I don't have a timeline of potential fix in hand though.

**Comment by Holo-Krzysztof** [comment]
Is there any news on this issue? This is a blocker for us and we want to move to OpenXR sooner rather than later since it's going to be the only option going forward with Unity 2021 LTS.

**Comment by yl-msft** [comment]
@Holo-Krzysztof , @WikkidEdd ,  This bug has been fixed in the Windows build and in the process of rolling out to customers.  Thanks for your patient.

**Comment by Holo-Krzysztof** [comment]
For reference, I got the info from support that it has been fixed in version 20348.1557.220601-1600. I'm currently in the process of updating a HoloLens to insider dev channel to check it out for myself; will report back later.
