### ISSUE TITLE
Spinning White Balls when pressing the power button then resuming app

### ISSUE THREAD

**Issue by WikkidEdd** [microsoft/OpenXR-Unity-MixedReality-Samples#53]
**Note: This issue has been moved from this other repo for better visibility https://github.com/WikkidEdd/OpenXRTestProject/issues/2**

## Describe the bug

When you press the power button of the HL2 when the app is running and then resume it can result in indefinitely seeing spinning white balls. This usually happens after one or two cycles of putting the device on standby and then resuming the app, but can sometimes take more attempts.

## To reproduce

1. Clone this git repo
2. Open Basic Sample Unity project
3. Switch to UWP build platform
4. Build the application.
5. Switch solution config to Release and ARM64
6. Build and Start the application
7. Wait until the app has started, wait 5 seconds, then short press on the power button to put the HL2 to sleep
8. Wait another 5 seconds, press the power button to wake up the device. Resume the app from the app slate in the world (or from the start menu if the app slate doesn't exist yet.
9. Repeat steps 7 and 8 until the app no longer resumes and shows the spinning white balls.

## Expected behavior

The application should resume without white spinning balls.

## Your setup (please complete the following information)

- Unity Version 2020.3.19
- Unity OpenXR Package 1.2.8
- Mixed Reality OpenXR Package 1.0.3 and 1.1.1 tested
- Holographic OS 20348.1432
- OpenXR Runtime Version 107.2109.10010.0

## Target platform (please complete the following information)
- HoloLens 2

## Additional context

If you run with the debugger attached when the problem occurs you will get an exception at the point you press the power button prior to seeing the white spinning balls.

Callstack (trimmed to make it more readable)
`GameAssembly.dll!OpenXRLoaderBase_Internal_EndSession
GameAssembly.dll!OpenXRLoaderBase_StopInternal
GameAssembly.dll!OpenXRLoaderBase_ReceiveNativeEvent
GameAssembly.dll!ReversePInvokeWrapper_OpenXRLoaderBase_ReceiveNativeEvent
GameAssembly.dll!OpenXRLoaderBase_Internal_PumpMessageLoop
GameAssembly.dll!OpenXRLoaderBase_ProcessOpenXRMessageLoop
GameAssembly.dll!_ClearLastSubmittedFrame_Invoke
GameAssembly.dll!BeforeRenderHelper_Invoke
GameAssembly.dll!Application_InvokeOnBeforeRender
GameAssembly.dll!RuntimeInvoker_FalseVoid
GameAssembly.dll!il2cpp::vm::Runtime::Invoke`

**Comment by yl-msft** [comment]
@WikkidEdd  the team has found fixes on this issue, and building a preview runtime to solve the problems of suspend resume.  We'd like to share a prerelease openxr runtime for you to try this out.  You can email me from my github profile for sharing the preview runtime package.

**Comment by yl-msft** [comment]
An update for this issue:
- For suspend/resume without power down HL2, the team found a fix in HL2 openxr runtime, and a fix in Unity's openxr plugin. The fix will be released in coming weeks. 
- The team is still investigating a similar but deeper issue when power off the HL2 and power on then resume the app. The team is looking for fixes in openxr runtime and unity's plugin and we will keep this thread posted when the fixes are determined.

**Comment by YXY1988** [comment]
Recently I also encounter this issue, and solved it by the following steps:
1. Upgrade the Unity version from 3.32 to 3.35.
2. Close the 'Research Mode' in the device portal webpage.
It worked for me.

**Comment by yl-msft** [comment]
@YXY1988   Thanks for reporting.  There are multiple issues in earlier versions of Unity that can manifest as "four spinning dots".  Some of the recent issues are captured in this "Blocking issues" documentation.  The one you were hitting was the due to the first row in the "resolved issues" table, and it was fixed in Unity 2020.3.35f1 and Unity 2021.3.4f1

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/known-issues#resolved-blocking-issues
