### ISSUE TITLE
XRAnchorStore not synced with SpatialAnchorStore 

### ISSUE THREAD

**Issue by otite** [microsoft/OpenXR-Unity-MixedReality-Samples#60]
The XRAnchorStore loaded with the XRAnchorStore.LoadAsync() function doesn't contains anchors saved in SpatialAnchorStore with the SpatialAnchorStore.TrySave() function.

I need to restart my app to get the imported anchors.
Reloading the XRAnchorStore does not do the trick.
Reinstanciating the ARSession neither.

Expected behavior : The XRAnchorStore  should be synced with the SpatialAnchorStore.

**Comment by yl-msft** [comment]
@otite , do you have a project that can show the bug above and share with us?  It can help us understand the bug and diagnose for you.

**Comment by yl-msft** [comment]
@otite , do you still observe the challenge you mentioned above?   If so, could you help us to get more information so we can better help you?   The XRAnchorStore in the BasicSample app works fine on HoloLens2.  I wonder if there's any misunderstanding that we didn't get what you were reporting.  Let us know.

**Comment by yl-msft** [comment]
@otite ,  we will need more details to help you, a repo unity project? or step by step? or sample code snippet?   The anchor sample in the BasicSample project demoed the usage of TrySave().   Closing this issue.  If you still see the bug, feel free to reopen with more details.
