### ISSUE TITLE
Holographic Remoting Instantly Disconnects

### ISSUE THREAD

**Issue by IanMcAtee** [microsoft/OpenXR-Unity-MixedReality-Samples#65]
Hi guys, I'm having issues with the holographic remoting aspect of the basic sample app. 

**ISSUE:**
Upon attempting to connect the HAR player app and the remote app on PC, the HAR player app will display connecting for a few seconds, but then disconnect. On the remote app, it will begin connecting for a second and I can see the basic sample menu appear for a moment, but then immediately disconnects yielding a disconnect message of "Disconnected to XX.XXX.XX. Reason is None".

**EXPECTED BEHAVIOR:**
Upon clicking connect in the remote app with the HAR player in "listen" mode or upon launching the HAR player in "connect" mode with the remote app in "listen" mode, the basic sample app should begin streaming on the HoloLens. 

**HARDWARE, SOFTWARE, AND SETTINGS USED:** 
Hardware: 
- HoloLens 2 
- Windows 10 PC (CPU: Intel i7 8700, GPU: NVIDIA GeForce GTX 1070)

Software: 
- Unity 2020.3.30
- Holographic Remoting Player v2.7.4.0
- HAR Sample Player from https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/main/player/sample/SamplePlayer.sln

Unity Settings: 
- Packages Used
![Packages](https://user-images.githubusercontent.com/29516514/156895608-9874ae7d-db71-4ef0-8bab-9369b90e166c.PNG)

- OpenXR UWP Settings
![OpenXRUWP](https://user-images.githubusercontent.com/29516514/156895720-430bb6f5-a007-4baf-b373-3e580daf8023.PNG)

- OpenXR PC Standalone Settings
![OpenXRStandalone](https://user-images.githubusercontent.com/29516514/156895745-12fa9b32-c53f-499c-b040-c1e61e2dac9c.PNG)

- UWP Capabilities Settings
![Capabilities](https://user-images.githubusercontent.com/29516514/156895814-b2505c12-d1f7-49b9-b5d3-2962f4c482de.PNG)

- UWP Build Settings
![UWPBuild](https://user-images.githubusercontent.com/29516514/156895862-375296a9-ef12-4800-9b43-947459fc4b45.PNG)

- PC Standalone Build Settings
![PCBuild](https://user-images.githubusercontent.com/29516514/156895885-b24aedef-2265-47c3-9cc3-8c760cbe9df6.PNG)

**SOLUTIONS ATTEMPTED:**
- Built the remote app both as a UWP and Win32 app, both exhibit same issue
- Tried the HAR sample app in both listen and connect modes using the command line arguments in visual studio. Both modes attempt to connect (displays connecting) then instantly disconnect
- Tried using the production HAR app from the Microsoft store while using remote app in connect mode. Same issue of instant disconnection encountered. 
- Ensured both remote app and visual studio were allowed though windows firewall
- Double checked OpenXR settings against read me documentation provided here

**SIMILAR REMOTING ISSUE:**
I've encountered a similar issue while attempting to use the holographic remoting for play mode in Unity. While attempting to do this, the HAR app also displays connecting for a second, then immediately disconnects and the scene begins playing in Unity game view as normal. Details of that issue can be found in the comment in my name (posted two days ago) in the following issue: https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/issues/50

Thanks for all your help and any information you could provide regarding this issue would be greatly appreciated. 

-Ian

**Comment by yl-msft** [comment]
@IanMcAtee , i saw the above screenshot you you reported on the HolographicRemoting-Samples repo were using "Mixed Reality OpenXR plugin" version 1.0.2  which is a bit old.  But on this report you showed a different screenshot with version 1.3.1.   I just want to double check that you did upgrade to the latest MR openxr plugin 1.3.1 and still see the similar problems.

I have another question.  Instead of using Unity, have you tried the remote app built in C++ using the sample repo on GitHub?
https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote

Get a result using these C++ sample apps can give us an indication which layer might need next level of investigation.  Thanks!

**Comment by IanMcAtee** [comment]
**Solved**
@yl-msft Thank you for the response, turns out all I had to do was update my graphics drivers. It's always something that simple...
