### ISSUE TITLE
Hand Mesh doesn't appear in HandTracking scene

### ISSUE THREAD

**Issue by GregBahm** [microsoft/OpenXR-Unity-MixedReality-Samples#74]
I am attempting to see the Hand Mesh visualization in the Hand Tracking scene using Holographic Remoting for Play Mode. The hand joints are tracking like they should, but toggling "Hand Mesh" on and off does nothing. In HandMesh.cs, the method on line 35,  handMeshTracker.TryGetHandMesh(FrameTime.OnUpdate, mesh), always returns false.

**Comment by keveleigh** [comment]
This is expected because the hand mesh API unfortunately isn't supported by the remoting runtime. You can see which features are unsupported at https://docs.microsoft.com/windows/mixed-reality/develop/native/holographic-remoting-troubleshooting#limitations

**Comment by GregBahm** [comment]
I see. Thanks!
