### ISSUE TITLE
Missing Controller.Velocity on Hololens2

### ISSUE THREAD

**Issue by Kris-Daniel** [microsoft/OpenXR-Unity-MixedReality-Samples#75]
If I inherit from IMixedRealityTouchHandler, implement needed methods, and try to get eventData.Controller.Velocity, I will get Vector3.zero. So here _velocityVector will work only in UnityEditor. On Hololens 2 it will be equal to Vector3.zero. Installed OpenXR Plugin 1.4.1. Unity Version 2020.3.33f1
![image](https://user-images.githubusercontent.com/32267848/165702739-b8c4a94a-3d52-43a4-be76-ba3693a9326d.png)

**Comment by yl-msft** [comment]
@Kris-Daniel , the openxr runtime team has investigated on this issue and have determined there was a bug in the runtime that didn't surface the hand tracking velocity properly.

In the latest 111 openxr runtime release, the velocity is hooked up.  Note that on HL2, the optical tracking for hand doesn't provide angular velocity, therefore the angular velocity value is always (0,0,0,0) and doesn't have "TRACKED" bits.

Please refer to this document to get preview runtime and try this out.  Thanks
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started#using-preview-extensions
